/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.quyen.qlhv.views;
import java.text.SimpleDateFormat;
import com.quyen.qlhv.model.Lophoc;
import com.quyen.qlhv.service.LophocServiceImpl;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Vutha
 */
public class addClassForm extends javax.swing.JPanel {
     public boolean validateFields() {
        if (!available.isSelected() && !unavailable.isSelected()) {
            return false; // Không có radio button nào được chọn
        }

        if (id.getText().trim().isEmpty() || courseId.getText().trim().isEmpty() || dateRegistered.getText().trim().isEmpty() ||name.getText().trim().isEmpty()) {
            return false; // Có trường bị bỏ trống
        }

        if (!isDateValid(dateRegistered.getText().trim())) {
            return false; // Kiểm tra định dạng ngày
        }

        try {
            Integer.parseInt(id.getText().trim()); // Kiểm tra Id
            Integer.parseInt(courseId.getText().trim()); // Kiểm tra courseId
        } catch (NumberFormatException e) {
            return false; // Id hoặc courseId không phải là số int
        }

        return true; // Tất cả các điều kiện đều đúng
    }

    private boolean isDateValid(String date) {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            sdf.setLenient(false);
            sdf.parse(date);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }
    private Lophoc returnObj() {
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Lophoc lophoc = new Lophoc();
    try {
        lophoc.setId(Integer.parseInt(id.getText().trim()));
        lophoc.setName(name.getText().trim());
        lophoc.setKhoahoc(Integer.parseInt(courseId.getText().trim()));
        lophoc.setStart_register(dateFormat.parse(dateRegistered.getText().trim()));
        lophoc.setStatus(available.isSelected());

        return lophoc;
    } catch (ParseException | NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Lỗi định dạng dữ liệu: " + e.getMessage());
        return null;
    }
}

    /**
     * Creates new form addClassForm
     */
    public addClassForm() {
       
        initComponents();
        
        id.setText("");
    name.setText("");
    courseId.setText("");
    dateRegistered.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        courseId = new javax.swing.JTextField();
        dateRegistered = new javax.swing.JTextField();
        unavailable = new javax.swing.JRadioButton();
        available = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        name = new javax.swing.JTextField();

        jLabel1.setText("Id");

        jLabel2.setText("Name");

        jLabel3.setText("Course Id");

        jLabel4.setText("Date registered");

        jLabel5.setText("Status");

        id.setText("jTextField1");

        courseId.setText("jTextField2");

        dateRegistered.setText("jTextField3");

        unavailable.setText("unavailable");
        unavailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unavailableActionPerformed(evt);
            }
        });

        available.setText("available");
        available.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        name.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(btnAdd)
                        .addGap(75, 75, 75)
                        .addComponent(btnReset))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(10, 10, 10))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id)
                                    .addComponent(name)
                                    .addComponent(courseId)
                                    .addComponent(dateRegistered)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(available)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(308, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(unavailable)
                .addGap(296, 296, 296))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(courseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dateRegistered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(unavailable)
                    .addComponent(available))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnReset))
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void unavailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unavailableActionPerformed
        // TODO add your handling code here:
             if (available.isSelected()) {
            unavailable.setSelected(false);
        }
    }//GEN-LAST:event_unavailableActionPerformed

    private void availableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableActionPerformed
        // TODO add your handling code here:
if (unavailable.isSelected()) {
            available.setSelected(false);
        }
    }//GEN-LAST:event_availableActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        id.setText("");
        name.setText("");
        dateRegistered.setText("");
        courseId.setText("");
        unavailable.setSelected(false);
        available.setSelected(false);
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
         if(!validateFields()){
        JOptionPane.showMessageDialog(null, "Sai định dạng dữ liệu");
    } else {
        Lophoc lophoc = returnObj();
        if (lophoc != null) {
            // Giả sử bạn có một instance của class chứa phương thức update, ví dụ: lopHocService
            LophocServiceImpl lopHocService = new LophocServiceImpl();
            boolean isUpdated = lopHocService.insert(lophoc);
            if (isUpdated) {
                JOptionPane.showMessageDialog(null, "Cập nhật lớp học thành công!");
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật lớp học thất bại!");
            }
        }
    }
        
        
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton available;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField courseId;
    private javax.swing.JTextField dateRegistered;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton unavailable;
    // End of variables declaration//GEN-END:variables
}
