/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.quyen.qlhv.views;

import java.text.SimpleDateFormat;
import com.quyen.qlhv.model.Lophoc;
import com.quyen.qlhv.service.LophocServiceImpl;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Vutha
 */
public class editClassroom extends javax.swing.JPanel {

    /**
     * Creates new form editClassroom
     */
    public editClassroom() {
        initComponents();
    }

    public void setData(Lophoc lophoc) {
        Id.setText(String.valueOf(lophoc.getId()));
        Id.setEnabled(false);
        name.setText(lophoc.getName());
        courseId.setText(String.valueOf(lophoc.getKhoahoc()));
        if (lophoc.isStatus() == true) {
            unavailableJRadioButton.setSelected(false);
            availableJRadioButton2.setSelected(true);

        } else {
            unavailableJRadioButton.setSelected(true);
            availableJRadioButton2.setSelected(false);
        }
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        dateRegistered.setText(dateFormat.format(lophoc.getStart_register()));
        

    }
    public boolean validateFields() {
        if (!availableJRadioButton2.isSelected() && !unavailableJRadioButton.isSelected()) {
            return false; // Không có radio button nào được chọn
        }

        if (Id.getText().trim().isEmpty() || courseId.getText().trim().isEmpty() || dateRegistered.getText().trim().isEmpty() || name.getText().trim().isEmpty()) {
            return false; // Có trường bị bỏ trống
        }

        if (!isDateValid(dateRegistered.getText().trim())) {
            return false; // Kiểm tra định dạng ngày
        }

        try {
            Integer.parseInt(Id.getText().trim()); // Kiểm tra Id
            Integer.parseInt(courseId.getText().trim()); // Kiểm tra courseId
        } catch (NumberFormatException e) {
            return false; // Id hoặc courseId không phải là số int
        }

        return true; // Tất cả các điều kiện đều đúng
    }

    private boolean isDateValid(String date) {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            sdf.setLenient(false);
            sdf.parse(date);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }
    private Lophoc returnObj() {
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Lophoc lophoc = new Lophoc();
    try {
        lophoc.setId(Integer.parseInt(Id.getText().trim()));
        lophoc.setName(name.getText().trim());
        lophoc.setKhoahoc(Integer.parseInt(courseId.getText().trim()));
        lophoc.setStart_register(dateFormat.parse(dateRegistered.getText().trim()));
        lophoc.setStatus(availableJRadioButton2.isSelected());

        return lophoc;
    } catch (ParseException | NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Lỗi định dạng dữ liệu: " + e.getMessage());
        return null;
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewpANE = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        courseId = new javax.swing.JTextField();
        dateRegistered = new javax.swing.JTextField();
        Id = new javax.swing.JTextField();
        unavailableJRadioButton = new javax.swing.JRadioButton();
        availableJRadioButton2 = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();

        jLabel1.setText("Name");

        jLabel2.setText("Id");

        jLabel3.setText("Date registered");

        jLabel4.setText("Status");

        jLabel5.setText("Mã khóa học");

        name.setText("jTextField1");

        courseId.setText("jTextField1");

        dateRegistered.setText("jTextField1");

        Id.setText("jTextField1");

        unavailableJRadioButton.setText("unavailable");

        availableJRadioButton2.setText("available");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewpANELayout = new javax.swing.GroupLayout(viewpANE);
        viewpANE.setLayout(viewpANELayout);
        viewpANELayout.setHorizontalGroup(
            viewpANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewpANELayout.createSequentialGroup()
                .addGroup(viewpANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewpANELayout.createSequentialGroup()
                        .addGroup(viewpANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewpANELayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel2))
                            .addGroup(viewpANELayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel1))
                            .addGroup(viewpANELayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel5))
                            .addGroup(viewpANELayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(viewpANELayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel4)))
                        .addGap(40, 40, 40)
                        .addGroup(viewpANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewpANELayout.createSequentialGroup()
                                .addComponent(unavailableJRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(availableJRadioButton2))
                            .addGroup(viewpANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                .addComponent(courseId)
                                .addComponent(dateRegistered)
                                .addComponent(Id))))
                    .addGroup(viewpANELayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnSave)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        viewpANELayout.setVerticalGroup(
            viewpANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewpANELayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(viewpANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(viewpANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(viewpANELayout.createSequentialGroup()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(viewpANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(courseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(viewpANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateRegistered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(viewpANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(viewpANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(unavailableJRadioButton)
                        .addComponent(availableJRadioButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(viewpANE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(0, Short.MAX_VALUE)
                .addComponent(viewpANE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
      if(!validateFields()){
        JOptionPane.showMessageDialog(null, "Sai định dạng dữ liệu");
    } else {
        Lophoc lophoc = returnObj();
        if (lophoc != null) {
            // Giả sử bạn có một instance của class chứa phương thức update, ví dụ: lopHocService
            LophocServiceImpl lopHocService = new LophocServiceImpl();
            boolean isUpdated = lopHocService.update(lophoc);
            if (isUpdated) {
                JOptionPane.showMessageDialog(null, "Cập nhật lớp học thành công!");
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật lớp học thất bại!");
            }
        }
    }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JRadioButton availableJRadioButton2;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField courseId;
    private javax.swing.JTextField dateRegistered;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton unavailableJRadioButton;
    private javax.swing.JPanel viewpANE;
    // End of variables declaration//GEN-END:variables
}
