/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quyen.qlhv.views;

import LIB.FadeEffect;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Jose Gpe Perez
 */
public class Form_LogIn extends javax.swing.JFrame {

    /**
     * Creates new form Form_LogIn
     */
    public Form_LogIn() {
        initComponents();
        FadeEffect.transp(Form_LogIn.this);
        FadeEffect.fadeInFrame(this, 15, 0.5f);
   
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jEImagePanel1 = new LIB.JEImagePanel();
        jEImagePanel2 = new LIB.JEImagePanel();
        login_username = new LIB.JTexfieldPH_FielTex();
        login_password = new LIB.JTexfieldPH_Password();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelTransparente1 = new LIB.JPanelTransparente();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTexfieldPH_FielTex1 = new LIB.JTexfieldPH_FielTex();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondotransparente.png"))); // NOI18N
        jEImagePanel1.setLayout(new java.awt.GridBagLayout());

        jEImagePanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quyen/qlhv/images/wwww.jpg"))); // NOI18N
        jEImagePanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_username.setBackground(new Color(0,0,0,0));
        login_username.setBorder(null);
        login_username.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        login_username.setOpaque(true);
        login_username.setPhColor(new java.awt.Color(255, 255, 255));
        login_username.setPlaceholder("Username");
        jEImagePanel2.add(login_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 220, -1));

        login_password.setBackground(new Color(0,0,0,0));
        login_password.setBorder(null);
        login_password.setForeground(new java.awt.Color(255, 255, 255));
        login_password.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        login_password.setPhColor(new java.awt.Color(255, 255, 255));
        login_password.setPlaceholder("Password:");
        jEImagePanel2.add(login_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 220, -1));
        jEImagePanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 220, 20));
        jEImagePanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 220, 20));

        jPanelTransparente1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Log In");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelTransparente1.add(jLabel1, new java.awt.GridBagConstraints());

        jEImagePanel2.add(jPanelTransparente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 220, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Log In");
        jEImagePanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 310, 100));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quyen/qlhv/images/icons8_Delete_27px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jEImagePanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 30, 30));

        jTexfieldPH_FielTex1.setBackground(new Color(0,0,0,0));
        jEImagePanel2.add(jTexfieldPH_FielTex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 109;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jEImagePanel1.add(jEImagePanel2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_LogIn().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.JEImagePanel jEImagePanel1;
    private LIB.JEImagePanel jEImagePanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private LIB.JPanelTransparente jPanelTransparente1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private LIB.JTexfieldPH_FielTex jTexfieldPH_FielTex1;
    private LIB.JTexfieldPH_Password login_password;
    private LIB.JTexfieldPH_FielTex login_username;
    // End of variables declaration//GEN-END:variables
}
